import type { NextPage } from "next"
import Head from "next/head"
import Banner from "../modules/banner/Banner"
import Footer from "../modules/footer/Footer"
import Header from "../modules/header/Header"
import Section from "../modules/section/Section"
import Services from "../modules/services/Services"
import Showcase from "../modules/showcase/Showcase"
import Testimonial from "../modules/testimonial/Testimonial"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Wedding Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
      <Section />
      <Services />
      <Showcase />
      <Testimonial />
      <Footer />
    </div>
  )
}

export default Home
